# SPDX-FileCopyrightText: 2019 Stephen Ibanez
#
# SPDX-License-Identifier: Apache-2.0
BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = pod-topo/topology.json
DEFAULT_PROG = basic.p4

include ../../utils/Makefile
